server:
  port: 9072

spring:
  rabbitmq:
    host: 182.92.175.117
    port: 5672
    username: admin
    password: 123456
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual