server:
  port: 9071

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mq?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.examole.mq.boot.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  pattern:
    level: debug
